### ISSUE TITLE
ldap.UNWILLING_TO_PERFORM in dsctl instname dblib bdb2mdb

### ISSUE THREAD

**Issue by progier389** [389ds/389-ds-base#5398] opened 2022-08-04 15:58 UTC
**Issue Description**
Running dsctl instname dblib bdb2mdb ( or dsctl instname dblib mdb2bdb )
Does perform rightlty the migration then restart rightly the server then exit in error:
ERROR: Error: 97 - 1 - 53 - Server is unwilling to perform - [] - Unauthenticated binds are not allowed

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version:  main branch

**Steps to Reproduce**
1. Run:
dsctl instname dblib bdb2mdb

**Expected results**Clean exit without error.

**Additional context**
IMHO, The issue is that the migration process stops then restart the server and yje start tries to reopen the instance connection 
But I think that connect_instance connect with ldapi but does not enable ldapi in the instance object 
  so after the restart it tries to use plain ldap instead of ldapi and fails because  the credentials are not provided.

**Comment by progier389** [comment] 2024-06-28 17:36
Triaged: https://issues.redhat.com/browse/IDMDS-4495

**Comment by tbordaz** [comment] 2024-10-16 12:59
This bug is a duplicate of #6064 (bdb2mdb adding a test of 'has_changelog' and mdb2dbd restart the instance with 'post_open=false')

**Closed as completed by tbordaz** 2024-10-16 12:59 UTC
