### ISSUE TITLE
All FreeIPA tests fail against 389-ds-base git master

### ISSUE THREAD

**Issue by abbra** [389ds/389-ds-base#4786] opened 2021-05-31 07:07 UTC
https://github.com/freeipa-pr-ci2/freeipa/pull/938 -- all deployment tests fail. The same happened with 2.0.5 in Rawhide and F34 which were updated yesterday.

Example of a failed IPA deployment in CI: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/03d51c0a-c0bc-11eb-bdac-fa163e5aefa6/

Fedora Rawhide failure in OpenQA: https://openqa.fedoraproject.org/tests/899345#step/role_deploy_domain_controller/31

In all failures, there is the same pattern:
```
[29/May/2021:20:44:47.438495028 +0000] - ERR - plugin_dependency_startall - Failed to resolve plugin dependencies
[29/May/2021:20:44:47.440835365 +0000] - ERR - plugin_dependency_startall - object plugin IPA Topology Configuration is not started
```
which is leading to a failure to start 389-ds instance.

Example logs: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/03d51c0a-c0bc-11eb-bdac-fa163e5aefa6/test_integration-test_automember.py-TestAutounmembership-install/master.ipa.test/var/log/dirsrv/slapd-IPA-TEST/errors.gz

**Comment by tbordaz** [comment] 2021-05-31 07:57
Just for recording. No immediate guilty patch. I have a doubt (TBC) around [backward compatibility fix](https://github.com/389ds/389-ds-base/commit/4763e65124114bfded887e361fecb43a2e7b8d66). I expect Topology plugin to depend/check the replication plugin and to be impacted by this fix.

**Comment by abbra** [comment] 2021-05-31 09:34
Yes, I think this is due to explicit dependency on the previous name of the multisupplier plugin in the topology plugin configuration ldif file. Obviously, we need a fix that @mreynolds389 provided to IPA too but I wonder if there could be something on 389-ds side that would help here as well for older IPA version to not fail.

**Comment by abbra** [comment] 2021-05-31 11:29
I have a prototype fix in https://github.com/freeipa/freeipa/pull/5798 to modify the dependency name if we detect 389-ds with multisupplier replication plugin. This would make Mark's PR obsolete and should handle the change on 389-ds dynamically, hopefully.

**Comment by mreynolds389** [comment] 2021-05-31 13:12
I'm off today, but if IPA would please install my PR this problem would go away, and it would not require anything else from FreeIPA or DS backwards compatibility.  I've been asking for weeks for IPA to merge this PR and they have not.  Before we make more potentially unnecessary changes to DS, please test with my IPA PR and 2.0.5...

**Comment by abbra** [comment] 2021-05-31 13:41
As I pointed out in that PR, it breaks IPA working with older 389-ds. My PR solves this problem.  Hopefully, I'll merge it today.

**Comment by abbra** [comment] 2021-05-31 16:04
I am running a test on Rawhide against 389-ds nightly with my changes here: https://dev.azure.com/abbra1freeipa/freeipa/_build/results?buildId=547, GATING ServerReplicaCALessToCAFull_1_to_3 already has been able to install 389-ds on server and replica so my PR works just fine there. We have broken dogtag in Rawhide at the moment so KRA deployment fails so other tests that use KRA are failing.
https://github.com/freeipa/freeipa/pull/5798 shows that run against older 389-ds also succeeds. There is a failure in Azure CI which is partly due to unrelated crash in krb5kdc that I am investigating. The crash is due to a memory pressure forcing KDC to drop LDAPI connection mid-air, we've seen that before and fixed some of the paths that lead to it, this one is new.

**Comment by Firstyear** [comment] 2021-06-01 00:07
In this case, if you have a PR in freeipa, is there a need for this issue to be open against 389-ds?

**Comment by abbra** [comment] 2021-06-01 05:26
I think there is still one issue that needs to be addressed by 389-ds as IPA cannot fix that. When new 389-ds starts on existing IPA installation, plugins which reference 'Multimaster Replication Plugin' in their dependencies will fail to load and 389-ds instance will shutdown itself.

This is exactly what happened in those failed runs and it means `upgrade_205_fixup_repl_dep` and `upgrade_repl_plugin_name` routines in `ldap/servers/slapd/upgrade.c` are probably called in wrong order or a logic to detect rename in the `upgrade_repl_plugin_name` is incomplete. The fixup depends on `upgrade_repl_plugin_name` to set old plugin name in a static variable but if `upgrade_repl_plugin_name` called after the upgrade or didn't detect the upgrade at all, fixup process would simply skip renaming.
This can be seen in the original error log: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/03d51c0a-c0bc-11eb-bdac-fa163e5aefa6/test_integration-test_automember.py-TestAutounmembership-install/master.ipa.test/var/log/dirsrv/slapd-IPA-TEST/errors.gz only shows an upgrade of the BDB layer:
```
[31/May/2021:18:02:46.870635846 +0000] - INFO - bdb_config_upgrade_dse_info - create config entry from old config
```
and no upgrade messages from `upgrade_205_fixup_repl_dep` while there are plugins with dependencies to older replication plugin name. So the logic to trigger update of the dependencies is incomplete.

**Comment by abbra** [comment] 2021-06-01 08:17
I updated Fedora 34 bodhi request with a fixed FreeIPA version that includes the patch from https://github.com/freeipa/freeipa/pull/5798 and triggered OpenQA run:
https://openqa.fedoraproject.org/tests/overview?build=Update-FEDORA-2021-234a7eff94&distri=fedora&version=34&groupid=2
this test includes an upgrade situation from F33 to F34, so we will see how it survives this update.

**Comment by abbra** [comment] 2021-06-01 11:03
Ok, with my fixes all tests passed, including F33 -> F34 upgrade: https://openqa.fedoraproject.org/tests/900038#step/role_deploy_domain_controller_check/31, so I think we don't need the change on 389-ds side if both 389-ds and FreeIPA are to be upgraded.

**Comment by abbra** [comment] 2021-06-09 14:37
I am reopening this issue because it affects any IPA installation even with our updated 389-ds/freeipa version from Fedora 34 stable -- the issue identified in comment https://github.com/389ds/389-ds-base/issues/4786#issuecomment-851819734 still needs to be fixed in 389-ds.

**Comment by mreynolds389** [comment] 2021-06-09 15:10
So DS fixes the plugin name and dependencies at server up.  @abbra  So does this happen with an old version of IPA (without my IPA PR) where it adds the old dependencies after DS starts up?

**Comment by abbra** [comment] 2021-06-09 15:15
This happens with either one if 389-ds was offline at the upgrade time. A new version of IPA is installed but not yet started because an update of the data is needed. To do update, it starts new 389-ds and that one simply fails to start because of that upgrade bug.

**Comment by mreynolds389** [comment] 2021-06-09 15:56
@abbra Can you provide the dse.ldif that is not being converted correctly at DS startup?

**Comment by abbra** [comment] 2021-06-09 16:38
@adelton has a reproducer with freeipa-container upgrade from F32 to F34. I'll ask him tomorrow.

**Comment by adelton** [comment] 2021-06-10 08:19
@mreynolds389 Which file exactly and from which time point should I show? Before I run `ipa-server-upgrade`, or after that `ipa-server-upgrade` fails at
```
Upgrading IPA:. Estimated time: 1 minute 30 seconds
  [1/9]: saving configuration
  [2/9]: disabling listeners
  [3/9]: enabling DS global lock
  [4/9]: disabling Schema Compat
  [5/9]: starting directory server
  [error] CalledProcessError: CalledProcessError(Command ['/bin/systemctl', 'start', 'dirsrv@EXAMPLE-TEST.service'] returned non-zero exit status 1: 'Job for dirsrv@EXAMPLE-TEST.service failed because the control process exited with error code.\nSee "systemctl status dirsrv@EXAMPLE-TEST.service" and "journalctl -xeu dirsrv@EXAMPLE-TEST.service" for details.\n')
  [cleanup]: stopping directory server
  [cleanup]: restoring configuration
IPA server upgrade failed: Inspect /var/log/ipaupgrade.log and run command ipa-server-upgrade manually.
Unexpected error - see /var/log/ipaupgrade.log for details:
CalledProcessError: CalledProcessError(Command ['/bin/systemctl', 'start', 'dirsrv@EXAMPLE-TEST.service'] returned non-zero exit status 1: 'Job for dirsrv@EXAMPLE-TEST.service failed because the control process exited with error code.\nSee "systemctl status dirsrv@EXAMPLE-TEST.service" and "journalctl -xeu dirsrv@EXAMPLE-TEST.service" for details.\n')
The ipa-server-upgrade command failed. See /var/log/ipaupgrade.log for more information
```

Also, would you like upgrade from Fedora 32, Fedora 33, or from Fedora 34 (previous versions of packages)?

**Comment by mreynolds389** [comment] 2021-06-10 11:40
I need to see the dse.ldif that prevents the DS from starting.

**Comment by adelton** [comment] 2021-06-10 13:45
Here's the /etc/dirsrv/slapd-EXAMPLE-TEST/dse.ldif from older Fedora 34 installation:

[dse.ldif.txt](https://github.com/389ds/389-ds-base/files/6631833/dse.ldif.txt)

**Comment by mreynolds389** [comment] 2021-06-10 13:55
> Here's the /etc/dirsrv/slapd-EXAMPLE-TEST/dse.ldif from older Fedora 34 installation:
> 
> [dse.ldif.txt](https://github.com/389ds/389-ds-base/files/6631833/dse.ldif.txt)

I think we need the newer dse.ldif that triggers the failure during upgrade (from 389-ds-base-2.0.5).  Can you please provide that dse.ldif as well?  Thanks

**Comment by adelton** [comment] 2021-06-11 09:10
Here's the /etc/dirsrv/slapd-EXAMPLE-TEST/dse.ldif after the attempted run of `ipa-server-upgrade`:
[dse.ldif2.txt](https://github.com/389ds/389-ds-base/files/6637209/dse.ldif2.txt)

**Comment by adelton** [comment] 2021-06-11 09:11
I tried to do a diff but the lines in the new one are two characters shorter, so there is too much noise.

**Comment by abbra** [comment] 2021-06-11 09:49
Interesting. So the new `dse.ldiff` looks ok -- it migrated all the dependencies and the replication plugin to a new naming. The only remaining mentions of the older plugin name are in creatorsName/modifiersName for some entries created by the replication plugin.

**Comment by adelton** [comment] 2021-06-11 14:16
The weird thing also is that rerunning `ipa-server-upgrade` the second time passes.

**Comment by mreynolds389** [comment] 2021-06-15 14:23
Ok I can reproduce the problem.  If a plugin with replication plugin dependency is processed before we rename the replication plugin this problem occurs.  Currently we only rename the plugin once we go to setup it up and start it, and in this case the IPA topology plugin is processed before we get to replication plugin.

**Comment by adelton** [comment] 2021-06-15 14:53
@mreynolds389 Thanks for the note. I was not able to reproduce the scenario outside of containers so it's good that it's not totally rare situation.

Is it expected that starting the `dirsrv@*.service` fails for the first time but then works the second time, that it self-heals?

**Comment by mreynolds389** [comment] 2021-06-15 16:02
> @mreynolds389 Thanks for the note. I was not able to reproduce the scenario outside of containers so it's good that it's not totally rare situation.
> 
> Is it expected that starting the `dirsrv@*.service` fails for the first time but then works the second time, that it self-heals?

Sort of, the DS upgrade code completes, but after the errors occurs.  So on the next DS startup attempt the config is finally correct and it starts up successfully.

**Comment by mreynolds389** [comment] 2021-06-17 14:23
This is now fixed upstream and it will be in our next nightly build.    Or https://copr.fedorainfracloud.org/coprs/g/389ds/389-ds-base-nightly/build/2257589/

This should fix the remaining issues we have around the replication plugin name change.  Please let me know the testing results from this build

**Comment by adelton** [comment] 2021-06-18 14:40
I confirm that the build 389-ds-base-2.0.5-20210617gitb251ffe74.fc34 fixes the upgrade problem in the freeipa-container scenario.

**Comment by adelton** [comment] 2022-01-02 07:51
Is something else needed to be done for this upgrade issue or did we conclude that all changes are already in?

**Comment by mreynolds389** [comment] 2023-01-26 14:51
This is over a year old and I have not heard of any new complaints.  Closing...

**Closed as completed by mreynolds389** 2023-01-26 14:51 UTC
