### ISSUE TITLE
python3-lib389 v1.4.3 seems to ignore the configuration parameters from /etc/openldap/ldap.conf

### ISSUE THREAD

**Issue by aivanov389** [389ds/389-ds-base#4460] opened 2020-11-25 14:15 UTC
**Issue Description**
python3-lib389 v1.4.3 seems to ignore the configuration parameters from /etc/openldap/ldap.conf. python3-lib389 v1.4.3 works fine.

**Package Version and Platform:**
 - Platform: CentOS 8.2.2004
 - Package and version: python3-lib389-1.4.3.13-1.module_el8+10475+b74bca99.noarch

**Steps to Reproduce**
1. Configure 389ds of any version (tested with 1.3.x and 1.4.x) with SSL enabled, disable non-secure binds (nsslapd-require-secure-binds: on). Let's take this 389ds server's  certificate signed with a self-signed CA my_ca.crt. Let's call this server ldap.example.com

2. Make a clean install of CentOS 8 + updates (resulting in updated CentOS 8.2.2004) on another server (management.example.com).

**_All the following actions are performed only on management.example.com (we do not touch anything on ldap.example.com):_**

3. [root@management ~]# dnf -y install openldap-clients

4. Do not touch the file /etc/openldap/ldap.conf (empty config from rpm) or put the following to force the usage of system pem bundle:
TLS_CACERT     /etc/pki/tls/cert.pem
TLS_REQCERT     demand

5. Install 389ds python libs and management tools v1.4.2:
[root@management ~]# dnf -y module enable 389-directory-server:stable
[root@management ~]# dnf -y install 389-ds-base
[root@management ~]# rpm -qi python3-lib389 | grep Version
----->Version     : 1.4.2.16

[root@management ~]# ldapsearch -LLL -x -H ldaps://ldap.example.com:636 -D "cn=Directory Manager" -w mypassword -b '' -s base defaultnamingcontext
----->ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)
_#This is ok since the ldap.example.com is signed by self-signed CA_

[root@management ~]# dsconf ldaps://ldap.example.com:636 -D "cn=Directory Manager" -w mypassword security get
----->Error: Can't contact LDAP server - error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed (self signed certificate in certificate chain)
_#This is ok since the ldap.example.com is signed by self-signed CA_
 
_#Now, install the self-signed CA to system bundle and check both connections (with ldapsearch and with dsconf) once again:_
[root@management ~]# trust anchor /path/to/my_ca.crt
[root@management ~]# ldapsearch -LLL -x -H ldaps://ldap.example.com:636 -D "cn=Directory Manager" -w mypassword -b '' -s base defaultnamingcontext
----->dn:
----->defaultnamingcontext: dc=example,dc=com
_#It works now - we have integrated the self-signed CA to system trusted certificate authorities bundle_

[root@management ~]# dsconf ldaps://ldap.example.com:636 -D "cn=Directory Manager" -w mypassword security get
-----> nsslapd-security: on
-----> nsslapd-securelistenhost: 
-----> nsslapd-secureport: 636
-----> nssslclientauth: allowed
-----> ...
_#It works now - we have integrated the self-signed CA to system trusted certificate authorities bundle and dsconf uses the configuration in /etc/openldap/ldap.conf_

6. If we delete now the the self-signed CA from system bundle (trust anchor --remove  /path/to/my_ca.crt) ldapsearch and dsconf will again generate the certificate errors and refuse to connect.
7. Now let us remove 389ds python libs and management tools v1.4.2 and install the v1.4.3 from testing repository:

[root@management ~]# dnf -y remove 389-ds-base  389-ds-base-libs python3-lib389
[root@management ~]# dnf -y module disable 389-directory-server:stable

[root@management ~]# dnf -y module enable 389-directory-server:testing
[root@management ~]# dnf -y install 389-ds-base
[root@management ~]# rpm -qi python3-lib389 | grep Version
----->Version     : 1.4.3.13

_#Install (if removed) the self-signed CA to system bundle and check ldapsearch:_
[root@management ~]# trust anchor /path/to/my_ca.crt
[root@management ~]# ldapsearch -LLL -x -H ldaps://ldap.example.com:636 -D "cn=Directory Manager" -w mypassword -b '' -s base defaultnamingcontext
----->dn:
----->defaultnamingcontext: dc=example,dc=com
_#It still works as expected since the self-signed CA is integrated to system trusted certificate authorities bundle_

_#Now test dsconf v1.4.3_
[root@management ~]# dsconf ldaps://ldap.example.com:636 -D "cn=Directory Manager" -w mypassword security get
----->Error: Can't contact LDAP server - error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed (self signed certificate in certificate chain)
_#dsconf v1.4.3 does not take into account the configuration in /etc/openldap/ldap.conf, though it may be made  to work using .dsrc file_

**Discussion**
There is a change in behavior between the versions of 1.4.2 and 1.4.3 of python3-lib389. In  version 1.4.3 the tools (at least dsconf) do not take into account the configuration (certificates and other options like TLS_REQCERT) from /etc/openldap/ldap.conf.
 This ticket is the follow-up of the discussion in 389ds users mailing list: https://lists.fedoraproject.org/archives/list/389-users@lists.fedoraproject.org/thread/GVKK5EGFPJQYVJACG5LK7S7ZMFAW3GFZ/

**Comment by aivanov389** [comment] 2020-11-26 15:56
I've tested this fix - it solves the problem partly: **TLS_REQCERT** in **/etc/openldap/ldap.conf**  is now taken into account but the CA certificates  parameter (**TLS_CACERT**) from /etc/openldap/ldap.conf  still does not work as it woked in 1.4.2

**Comment by aivanov389** [comment] 2020-11-26 16:57
I think i have found the part of the code that causes ignoring **TLS_CACERT**: it's the file __init__.py, lines 997-999:
```
 997         if certdir is None and self.isLocal:
 998             certdir = self.get_cert_dir()
 999             self.log.debug("Using dirsrv ca certificate %s", certdir)
```

if i comment these lines **dsconf** starts to take into account **TLS_CACERT** from **/etc/openldap/ldap.conf**. Looks like **self.isLocal** shoud not be **true** while it is, as a result a false certdir is taken: DEBUG: Using dirsrv ca certificate /Local/dirsrv/etc/dirsrv/slapd-{instance_name}
DEBUG: Using external ca certificate /Local/dirsrv/etc/dirsrv/slapd-{instance_name}
DEBUG: Using external ca certificate /Local/dirsrv/etc/dirsrv/slapd-{instance_name}

**Comment by aivanov389** [comment] 2020-11-26 17:52
After additional analysis looks like there is a line missing in the detection of isLocal code (lines 539-540 of `__init__.py`):
 ```
536         self.isLocal = True
 537         if SER_SERVERID_PROP not in args:
 538             self.log.debug('SER_SERVERID_PROP not provided, assuming non-local instance')
 539             # The lack of this value basically rules it out in most cases
```
**```+        self.isLocal = False```**
```
 540             self.ds_paths = Paths(instance=self, local=self.isLocal)
 541         else:
 542             self.ds_paths = Paths(serverid=args[SER_SERVERID_PROP], instance=self, local=self.isLocal)
 543             # Settings from args of server attributes
 544             self.serverid = args.get(SER_SERVERID_PROP, None)
 545             # Probably local?
 546             self.isLocal = True
```

**Comment by Firstyear** [comment] 2020-11-27 00:10
I don't think it's so simple. Because dsrc is passing in a server_id, it's still triggering the isLocal = true on line 546. Honestly I've been trying to stamp out the def allocate function from being used for years, but techdebt is like this ...

@droideck I think in this case we either need to swap connect_instance in cli_base/__init__.py to use local_simple_allocate or remote_simple_allocate, OR we need to have an extra argument to pass to def allocate that can force setting of isLocal. 

An extra complexity becomes that some people may rely on the current isLocal behaviour for dsconf + islocal + ldaps for automatic addition of the TLS cert dir into their instance.

**Comment by mreynolds389** [comment] 2020-12-01 17:14
FYI, dsconf using ldaps does not work locally either.   I don't have a .dsrc file, but it should just work on a default install from the same machine.

We're seeing bugs on this now from customers:

https://bugzilla.redhat.com/show_bug.cgi?id=1902303

**Comment by mreynolds389** [comment] 2020-12-01 21:33
And this bug which is slightly different:

https://bugzilla.redhat.com/show_bug.cgi?id=1903350

**Comment by mreynolds389** [comment] 2020-12-01 22:24
There is one bug with sign signed certs I found:

```
diff --git a/src/lib389/lib389/instance/setup.py b/src/lib389/lib389/instance/setup.py
index 4abc0433b..692ca35b7 100644
--- a/src/lib389/lib389/instance/setup.py
+++ b/src/lib389/lib389/instance/setup.py
@@ -888,7 +888,7 @@ class SetupDs(object):
                         tlsdb_inst = NssSsl(dbpath=os.path.join(etc_dirsrv_path, dir))
                         tlsdb_inst.import_rsa_crt(ca)
 
-            csr = tlsdb.create_rsa_key_and_csr()
+            csr = tlsdb.create_rsa_key_and_csr(alt_names=[general['full_machine_name']])
             (ca, crt) = ssca.rsa_ca_sign_csr(csr)
             tlsdb.import_rsa_crt(ca, crt)
             if general['selinux']:
```

But after this fix and my fix above, I got it working by settings up the .dsrc file like this:

```
[localhost]
tls_cacertdir = /etc/dirsrv/slapd-localhost
uri = ldaps://localhost.localdomain:636
```

**Comment by Firstyear** [comment] 2020-12-03 05:22
This PR is what Mark suggested, but it doesn't resolve this fully. We need to consider for the TLS cert problem

* TLS tests must be able to find the local SSCA dir automatically.
* dsctl needs to find the SSCA dir automatically to interact with it
* dsconf may be on a remote machine, or the same machine with a user without SSCA dir read access
* dsconf without a cacertdir should use the value in /etc/openldap/ldap.conf

This is pretty annoying to actually achieve because it relies on some weird autodetection and the isLocal flag, so I think quite a bit of testing would be needed to verify we haven't botched this.

**Comment by mreynolds389** [comment] 2020-12-03 15:27
Related bugzillas:

https://bugzilla.redhat.com/show_bug.cgi?id=1902303
https://bugzilla.redhat.com/show_bug.cgi?id=1903133

**Comment by Firstyear** [comment] 2020-12-10 03:11
@droideck and @mreynolds389 thoughts on my comments and how we should tackle this? I'm willing to do the code, but just want to be sure I haven't missed a use case ...

**Comment by mreynolds389** [comment] 2020-12-10 03:35
I think the most important thing here is that 1.4.x behaves exactly how 1.4.2 does.  So the full machine name fix should be pushed(definitely), but other behavior changes should be "reverted".  In 2.0.0 we can do things different if we want, but the 1.4.x series should be consistent.  I think the only outstanding issue is the TLS_CACERT not being honoured in post 1.4.2 as mentioned by @aivanov389 but I have not had a chance to look into it.

**Comment by mreynolds389** [comment] 2020-12-10 03:36
> I think the most important thing here is that 1.4.x behaves exactly how 1.4.2 does. So the full machine name fix should be pushed(definitely)

It was pushed already, nevermind  :-)

**Comment by tbordaz** [comment] 2021-03-25 09:40
@mreynolds389 any reason to keep this issue opened ?

**Comment by vashirov** [comment] 2021-03-25 10:09
@tbordaz, related RHDS bz was moved to ASSIGNED, as it's not fixed completely. I think we should keep it open for now.

**Comment by mreynolds389** [comment] 2021-03-25 12:49
I think this is fixed.  That bug that was moved back to ASSIGNED because they forget to setup the .dsrc file.  The problem is that when you use a LDAPURL with dsconf you are not specifying an instance.  So it has no idea if it the URL is local or not, and what slapd instance it is referring to.  Setting up the .dsrc file sets these defaults so it knows where to find the correct paths.

**Comment by mreynolds389** [comment] 2021-03-25 13:21
ok after rereading all of this, the last outstanding issue is that if .dsrc is not set, we still ignore what is in /etc/openldap/ldap.conf.  Previously dsconf would use ldap.conf for TLS info....

**Comment by droideck** [comment] 2021-07-27 15:59
Okay, the issue is not so simple as it may seem. So let me summarize the situation:

1. The simplest issue to fix is mentioned in this comment - https://github.com/389ds/389-ds-base/issues/4460#issuecomment-734425304
2. Then, William has noted other issues and the main problem (as it looks to me) is that we have an inconsistency with 'isLocal' identification. We assume that if a user calls 'dsconf INSTANCE_NAME' - he does it locally. But it's **not true** as the user may have ~/.dsrc which has the external instance set up and still it sets 'server-id' property;

    And then, when python-lib389 thinks that it's run locally - it tries to look for the certificates in cert_dir location (and sometimes we take the path from defaults.inf and sometimes from dse.ldif...);
3. On 1.4.2 we didn't process instance_name properly (and the bug was fixed only in 1.4.3) so we had a false success (the commands were successful as noted in the initial issue - even though the current bug still existed, though it was masked)

I was thinking a lot and I'm still opened for other suggestions but there is my solution proposal:

- We fix 1.4.3 configuration issue by this PR - https://github.com/389ds/389-ds-base/pull/4850:
  It fixes the first issue [1], and it adds an addtional check to DirSrv.open() which will make sure that the certdir (and other TLS paths) are accessible (has read right) before setting ldap.OPT_X_TLS_*. 
- We improve the existing PR (or I'll open another one) by one of these solutions:
  1. Add a new option to ~/.dsrc - "remote_instance = True" (which by default will be set to "False") or "local_instance = True" (which by default will be set to "False"). This way administrator (or user) will be able to define explicitly the behaviour he wants. And the users will always connect remotely (using TLS values from ldap.conf or ~/.dsrc)
  2. When we check for 'isLocal' - check if 'uri' has 'localhost' (and its variations) in it. If it has or 'uri' is not defined - 'isLocal = True'. And if it's True - then we can get the cert_dir from the local path (defaults.inf and dse.ldif)
  
What do you think, folks?

**Comment by droideck** [comment] 2021-08-03 12:50
The discussion is finished in the #4850 PR.

**Closed as completed by droideck** 2021-08-03 12:50 UTC
Labels: In JIRA, priority_high

**Comment by droideck** [comment] 2021-08-03 13:38
7b705e743..2141a54f6  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
   357c16cde..4bd1c9408  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
